graph TD
    subgraph Inputs
        A0 & B0 --> L1P0 & L1G0
        A1 & B1 --> L1P1 & L1G1
        A2 & B2 --> L1P2 & L1G2
        A3 & B3 --> L1P3 & L1G3
    end

    subgraph "Layer 1: Generate P and G, First level"
        L1P0[P0] & L1G0[G0]
        L1P1[P1] & L1G1[G1]
        L1P2[P2] & L1G2[G2]
        L1P3[P3] & L1G3[G3]
        L1P0 & L1P1 --> L1PP01[PP01]
        L1P2 & L1P3 --> L1PP23[PP23]
        L1P1 & L1G0 --> L1PG01[PG01]
        L1P3 & L1G2 --> L1PG23[PG23]
    end

    subgraph "Layer 2: Start OR and carry"
        L1G1 & L1PG01 --> L2GG01X[GG01_XOR]
        L1G3 & L1PG23 --> L2GG23X[GG23_XOR]
        L1PP01 & L1PP23 --> L2PPP[PPP]
        L1G0 & L1P0 & Cin --> L2C1X[C1_XOR]
    end

    subgraph "Layer 3: Complete first level, start second"
        L2GG01X --> L3GG01[GG01]
        L2GG23X --> L3GG23[GG23]
        L1PP23 & L3GG01 --> L3PPG[PPG]
        L3GG23 & L3PPG --> L3GGGX[GGG_XOR]
        L2C1X --> L3C1A[C1_AND]
        L3GG01 & L1PP01 & Cin --> L3C2X[C2_XOR]
    end

    subgraph "Layer 4: Progress second level and carries"
        L3GG23 & L3PPG --> L4GGGA[GGG_AND]
        L3C1A & L2C1X --> L4C1[C1]
        L3C2X --> L4C2A[C2_AND]
    end

    subgraph "Layer 5: Complete second level, progress carries"
        L3GGGX & L4GGGA --> L5GGG[GGG]
        L3C2X & L4C2A --> L5C2[C2]
        L5GGG & L2PPP & Cin --> L5C3X[C3_XOR]
    end

    subgraph "Layer 6: Progress carries and sum"
        L5C3X --> L6C3A[C3_AND]
        L1P0 & Cin --> L6S0[S0]
        L1P1 & L4C1 --> L6S1[S1]
    end

    subgraph "Layer 7: Finalize"
        L5C3X & L6C3A --> L7C3[C3]
        L1P2 & L5C2 --> L7S2[S2]
        L1P3 & L7C3 --> L7S3[S3]
    end

    L7C3 --> Cout[Carry_out]