[package]
name = "circuit-std-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
expander_compiler = { path = "../expander_compiler"}

ark-std.workspace = true
rand.workspace = true
expander_config.workspace = true
expander_circuit.workspace = true
gkr.workspace = true
arith.workspace = true
gf2.workspace = true
mersenne31.workspace = true
sha2 = "0.10.8"
big-int = "7.0.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
ark-bls12-381 = "0.5.0"
ark-ff = "0.5.0"
ark-ec = "0.5.0"
ark-serialize = { version = "0.5.0", features = ["std"] }
tiny-keccak = { version = "2.0.2", features = [ "sha3", "keccak" ] }
