[package]
name = "circuit-std-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
expander_compiler = { path = "../expander_compiler"}

arith.workspace = true
ark-std.workspace = true
expander_config.workspace = true
expander_circuit.workspace = true
gf2.workspace = true
gkr.workspace = true
halo2curves.workspace = true
mersenne31.workspace = true
rand.workspace = true